@startuml

title __VIEW's Class Diagram__\n

  namespace fr.insa.lyon.ifa1 {
    namespace view {
      class fr.insa.lyon.ifa1.view.DeliveryView {
          {static} - VIEW_CONTROLLER : ViewController
          + show()
      }
    }
  }
  

  namespace fr.insa.lyon.ifa1 {
    namespace view {
      class fr.insa.lyon.ifa1.view.ImportView {
          {static} - SCENE : Scene
          {static} - VIEW_CONTROLLER : ViewController
          + openFileChooser()
          + quit()
          + show()
      }
    }
  }
  

  namespace fr.insa.lyon.ifa1 {
    namespace view {
      class fr.insa.lyon.ifa1.view.MainView {
          {static} # SCENE : Scene
          {static} - DELIVERY_MEN_PATHS_COLORS : Color[]
          {static} - DELIVERY_MEN_PATHS_WIDTH : double
          {static} - DEPOT_COLOR : Color
          {static} - DEPOT_WIDTH : double
          {static} - MAP_SEGMENTS_COLOR : Color
          {static} - MAP_SEGMENTS_WIDTH : double
          {static} - OVERED_PASSAGE_POINTS_COLOR : Color
          {static} - OVERED_PASSAGE_POINTS_WIDTH : double
          {static} - PASSAGE_POINTS_COLORS : Color[]
          {static} - PASSAGE_POINTS_WIDTH : double
          {static} - VIEW_CONTROLLER : ViewController
          {static} - canvasOrigin : Map<String, Double>
          {static} - closestPassagePoint : Map<PassagePointType, Map<String, Double>>
          {static} - mapOrigin : Map<String, Double>
          {static} - ratio : Double
          {static} - realClosestPassagePoint : PassagePoint
          {static} - state : StateMainView
          + addPickup()
          + onCalculate()
          + onCanvasClick()
          + openFileChooser()
          + quit()
          + setState()
          + show()
          - clearCanvas()
          - drawAll()
          - drawDeliveryMenPaths()
          - drawMap()
          - drawOveredPassagePoints()
          - drawPassagePoints()
          - drawPoints()
          - drawSegments()
          - getMapCoordinatesFromWorldCoordinates()
          - getWorldCoordinatesFromMapCoordinates()
          - onDeletePassagePoint()
          - onHeightResize()
          - onMouseMove()
          - onWidthResize()
          - populateDeliveryData()
          - setCanvasOrigin()
          - setLoadingCursor()
          - setMapParameters()
          - showPopUpDurationPoint()
          - userAddPickupDeliveryDraw()
      }
    }
  }
  

  namespace fr.insa.lyon.ifa1 {
    namespace view {
      class fr.insa.lyon.ifa1.view.MainViewAddDeliveryState {
          + canvasClick()
      }
    }
  }
  

  namespace fr.insa.lyon.ifa1 {
    namespace view {
      class fr.insa.lyon.ifa1.view.MainViewAddPickupState {
          + canvasClick()
      }
    }
  }
  

  namespace fr.insa.lyon.ifa1 {
    namespace view {
      class fr.insa.lyon.ifa1.view.MainViewMovePointState {
          + MainViewMovePointState()
          + canvasClick()
      }
    }
  }
  

  namespace fr.insa.lyon.ifa1 {
    namespace view {
      class fr.insa.lyon.ifa1.view.MainViewWaitingState {
          + canvasClick()
      }
    }
  }
  

  namespace fr.insa.lyon.ifa1 {
    namespace view {
      interface fr.insa.lyon.ifa1.view.StateMainView {
          {abstract} + canvasClick()
      }
    }
  }
  

  namespace fr.insa.lyon.ifa1 {
    namespace view {
      interface fr.insa.lyon.ifa1.view.ViewInterface {
          {abstract} + show()
      }
    }
  }
  

  fr.insa.lyon.ifa1.view.DeliveryView .up.|> fr.insa.lyon.ifa1.view.ViewInterface
  fr.insa.lyon.ifa1.view.ImportView .up.|> fr.insa.lyon.ifa1.view.ViewInterface
  fr.insa.lyon.ifa1.view.MainView .up.|> fr.insa.lyon.ifa1.view.ViewInterface
  fr.insa.lyon.ifa1.view.MainViewAddDeliveryState .up.|> fr.insa.lyon.ifa1.view.StateMainView
  fr.insa.lyon.ifa1.view.MainViewAddPickupState .up.|> fr.insa.lyon.ifa1.view.StateMainView
  fr.insa.lyon.ifa1.view.MainViewMovePointState .up.|> fr.insa.lyon.ifa1.view.StateMainView
  fr.insa.lyon.ifa1.view.MainViewMovePointState o-- fr.insa.lyon.ifa1.models.request.PassagePoint : pointToMove
  fr.insa.lyon.ifa1.view.MainViewWaitingState .up.|> fr.insa.lyon.ifa1.view.StateMainView


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
