@startuml

title __ALGO's Class Diagram__\n

  namespace fr.insa.lyon.ifa1 {
    namespace algo {
      interface fr.insa.lyon.ifa1.algo.AddPickupAndDelivery {
          {abstract} + solve()
      }
    }
  }
  

  namespace fr.insa.lyon.ifa1 {
    namespace algo {
      class fr.insa.lyon.ifa1.algo.AddPickupAndDeliveryImpl {
          + solve()
          - addPoint()
          - computeTripletLength()
      }
    }
  }
  

  namespace fr.insa.lyon.ifa1 {
    namespace algo {
      class fr.insa.lyon.ifa1.algo.Dijkstra {
          + getSuccesors()
          + solve()
          + solveOne()
          - computeShortestRoutes()
          - extractRoute()
          - extractRoutes()
          - initialize()
      }
    }
  }
  

  namespace fr.insa.lyon.ifa1 {
    namespace algo {
      interface fr.insa.lyon.ifa1.algo.FindShortestHamiltonianCircuit {
          {abstract} + solve()
      }
    }
  }
  

  namespace fr.insa.lyon.ifa1 {
    namespace algo {
      interface fr.insa.lyon.ifa1.algo.FindShortestRoutes {
          {abstract} + solve()
      }
    }
  }
  

  namespace fr.insa.lyon.ifa1 {
    namespace algo {
      class fr.insa.lyon.ifa1.algo.FindShortestRoutes.Route {
          - destination : String
          - itinerary : List<Segment>
          - length : double
          - origin : String
          + Route()
          + getDestination()
          + getItinerary()
          + getLength()
          + getOrigin()
      }
    }
  }
  

  namespace fr.insa.lyon.ifa1 {
    namespace algo {
      class fr.insa.lyon.ifa1.algo.OptimalHamiltonianCircuit {
          - optimalLength : double
          - optimalRoute : List<PassagePoint>
          - routes : Map<String, Map<String, Route>>
          - startTime : long
          - timeLimitInMilliseconds : long
          + OptimalHamiltonianCircuit()
          + solve()
          - visitePoint()
      }
    }
  }
  

  fr.insa.lyon.ifa1.algo.AddPickupAndDeliveryImpl .up.|> fr.insa.lyon.ifa1.algo.AddPickupAndDelivery
  fr.insa.lyon.ifa1.algo.Dijkstra .up.|> fr.insa.lyon.ifa1.algo.FindShortestRoutes
  fr.insa.lyon.ifa1.algo.FindShortestRoutes +-down- fr.insa.lyon.ifa1.algo.FindShortestRoutes.Route
  fr.insa.lyon.ifa1.algo.OptimalHamiltonianCircuit .up.|> fr.insa.lyon.ifa1.algo.FindShortestHamiltonianCircuit
  fr.insa.lyon.ifa1.algo.OptimalHamiltonianCircuit o-- fr.insa.lyon.ifa1.models.request.PlanningRequest : pr


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
